// Teaching examples only. These entries describe boundaries, not live connections.
export const tools = [
  {id:'anza',location:'Local setup CLI, on the machine where the project is prepared.',name:'Anza',role:'Prepare a repeatable place to build.',owns:'Project setup and the environment needed to start.',excludes:'Hands the prepared project to the workflow. Setup does not approve coding, cloud spend or publication.',maturity:'Local setup tooling exists. Native, provider and release qualification remain separate work.'},
  {id:'foundry',location:'One private controller. A local workshop instance is the starting profile; hosted operation needs its own qualified environment.',name:'Foundry',role:'Own the product workflow, from a scoped plan to a qualified release.',owns:'Scope, acceptance criteria, task dependencies, budgets and product readiness. Review and merge are tasks in the plan.',excludes:'Delegates bounded coding to a harness or Kazi, and independent review to APRL or a reviewer. Merge does not grant deployment permission.',maturity:'Internal components exist. The full public execution and release workflow is not qualified as a live service.'},
  {id:'kazi',location:'Local CLI or inside an isolated worker. Optional AWS coding workers need bounded authorization and return patches to the controller.',name:'Kazi',role:'Work toward a bounded goal with observable checks.',owns:'A scoped coding task, correction attempts and evidence from its stated predicates.',excludes:'Returns a candidate and check evidence. A passing predicate does not replace independent review or authorize a merge.',maturity:'Local goal execution exists. Use depends on the project and the checks available; a direct harness is also an option.'},
  {id:'aprl',location:'Proposed review broker. A local service would need a qualified webhook relay or polling; a hosted service would receive webhooks at its approved endpoint.',name:'APRL',role:'Broker independent candidate review and GitHub handoffs.',owns:'The proposed review boundary: inspect the exact candidate before publication, then honor required PR checks and merge gates.',excludes:'Reports findings to the workflow. It does not own the product plan, repeat the coding task graph or deploy the product.',maturity:'Planned service; no implementation is claimed. An independent reviewer can carry out this step today.'},
  {id:'amos',location:'Application framework: local preview during learning, then the product’s separately qualified hosting target.',name:'AMOS',role:'Provide the application framework for the product people use.',owns:'Application behavior, compatible runtime capabilities and a place to observe what needs improvement.',excludes:'Feedback becomes a new scoped change in the product workflow. The application runtime does not become another coding controller.',maturity:'Framework work and local evaluation exist. Full SaaS, provider and deployment readiness are not established.'}
];
export const stages = [
  {id:'prepare',title:'Prepare',node:'anza',eyebrow:'PREPARE / ANZA',headline:'Start with a place to build.',description:'Set up the project and agree what you are working on. Anza illustrates the setup role: make the first step repeatable before asking AI to change anything.',benefit:'Spend less time repeating setup. Start from a project you can explain and return to.',artifact:'A prepared project and short setup notes.',check:'Can you open the project and repeat the setup without guessing?',boundary:'Setup consent is separate from permission to code, spend or publish.',prompt:'What would someone else need to start this project tomorrow?',exercise:'Open the example project. Identify its starting command and what a successful start looks like.'},
  {id:'plan',title:'Plan',node:'foundry',eyebrow:'PLAN / FOUNDRY',headline:'Give the idea a finish line.',description:'Choose one useful change. For a booking request, define what is saved, what must be rejected and how you will know. Plan the review and merge work at the same time.',benefit:'A smaller task and a shared meaning of done. Catch unclear requirements before they become repeated work.',artifact:'A scoped plan with build, review and merge tasks, checks and a time limit.',check:'A valid request is recorded; missing contact details are rejected; resending does not create a duplicate.',boundary:'Foundry owns the product workflow. Each task has one owner, an input and an observable result.',prompt:'What is the smallest useful booking flow, and what are we leaving for later?',exercise:'Write three acceptance checks: a normal request, missing contact details and the same request sent twice.'},
  {id:'build',title:'Build',node:'kazi',eyebrow:'BUILD / KAZI OR YOUR HARNESS',headline:'Make one useful change.',description:'Direct AI with the scope and checks. Inspect a candidate, run the relevant checks and correct failures within the agreed limits. Kazi illustrates bounded work toward a measurable goal.',benefit:'A change you can inspect, with evidence you can use to decide what happens next.',artifact:'An isolated candidate patch and the actual check results.',check:'Inspect both the behavior and the diff. A failed check returns to the same bounded task.',boundary:'Workers return candidates. They do not receive general cloud authority or permission to push, merge or deploy.',prompt:'Which part did the agent change, and what evidence supports that change?',exercise:'Use the duplicate-check illustration below. Keep the acceptance criterion unchanged while the candidate is corrected.'},
  {id:'review',title:'Review',node:'aprl',eyebrow:'REVIEW / INDEPENDENT SECOND LOOK',headline:'Check the exact candidate.',description:'Give another reviewer the candidate and its evidence before opening the PR. APRL illustrates that review boundary. Resolve findings, then publish the reviewed candidate for the required GitHub checks.',benefit:'Catch assumptions early. Make the handoff easier to understand because the reviewer sees the same change and evidence.',artifact:'Findings tied to the candidate revision, plus a reviewed patch ready for PR checks.',check:'Was this exact revision reviewed? If the candidate changes, review the affected work again.',boundary:'Pre-PR review is one gate. Required CI, repository approvals and merge rules still apply after the PR.',prompt:'What could the implementation author have missed even if the stated checks pass?',exercise:'Ask another person to inspect the duplicate behavior and rejection path. Record one finding or the limits of the review.'},
  {id:'release',title:'Release',node:'foundry',eyebrow:'RELEASE / FOUNDRY',headline:'Decide what is ready to ship.',description:'Bring the evidence back to the product workflow. Complete the merge task only when its gates pass. Separately qualify the actual artifact and environment before a deployment decision.',benefit:'Control over what reaches people. A clear record of what was approved and what remains unverified.',artifact:'A merged change, or a documented blocker; deployment evidence and approval if release is in scope.',check:'Are the required checks satisfied for this revision? Is the deployment artifact and target environment qualified?',boundary:'Merge and deployment are separate tasks. Release permission is tied to the actual artifact and environment.',prompt:'What evidence would make you comfortable sharing this result with someone else?',exercise:'Sort the evidence into local behavior, PR checks and deployment readiness. Mark any gaps before deciding.'},
  {id:'improve',title:'Improve',node:'amos',eyebrow:'IMPROVE / YOUR APPLICATION',headline:'Make the next change yourself.',description:'Use the result, observe what people need and keep a record of what you learned. AMOS illustrates the application framework. Send the next useful change back to the plan.',benefit:'A repeatable way to keep improving. Practice judgment you can use after the workshop.',artifact:'A small useful result, known limits and a next-change note.',check:'Can you explain the result, repeat its checks and make a second small change?',boundary:'Application feedback informs the next plan. Your project determines the tools; this map does not claim live integrations.',prompt:'What would you improve next, and what evidence tells you it matters?',exercise:'Make one second change. Note what you did independently, where a hint helped and where the instructor stepped in.'}
];
