// A conceptual teaching map. These nodes do not run agents or change software.
export const observed = '2026-10-03';
export const sources = [
 {id:'api',name:'OpenAPI Initiative · API contracts',url:'https://spec.openapis.org/oas/latest.html',date:'Living specification',claim:'Describes a machine-readable interface to HTTP APIs. A contract makes a capability discoverable; it does not grant permission or prove that it works.'},
 {id:'mcp',name:'Model Context Protocol · Architecture',url:'https://modelcontextprotocol.io/docs/learn/architecture',date:'Versioned documentation',claim:'Defines hosts, clients and servers exposing tools, resources and prompts. Connecting tools is one part of an agent system, not a complete governance or improvement system.'},
 {id:'agents',name:'Anthropic · Building effective agents',url:'https://www.anthropic.com/engineering/building-effective-agents',date:'19 Dec 2024 · foundational patterns',claim:'Distinguishes predefined workflows from agents directing tool use, and describes environment feedback and stopping conditions. Its tooling examples have changed since publication.'},
 {id:'harness',name:'Anthropic · Long-running agent harnesses',url:'https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents',date:'26 Nov 2025',claim:'Describes incremental work, durable progress artifacts and checking features across sessions. Long-running work needs more than a high-level prompt.'},
 {id:'evals',name:'Anthropic · Evaluating agents',url:'https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents',date:'9 Jan 2026',claim:'Explains how evaluations expose behavioral changes and failures before users encounter them. Evaluation design must match the system and task.'},
 {id:'managed',name:'Anthropic · Managed agent architecture',url:'https://www.anthropic.com/engineering/managed-agents',date:'8 Apr 2026',claim:'Separates sessions, the agent harness and execution sandboxes. This is a concrete industry example of separating reasoning, state and execution.'},
 {id:'evolve',name:'Google DeepMind · AlphaEvolve',url:'https://deepmind.google/blog/alphaevolve-a-gemini-powered-coding-agent-for-designing-advanced-algorithms/',date:'14 May 2025',claim:'Combines generated code with automated evaluators for measurable algorithm improvements. This demonstrates a bounded approach; it does not establish autonomous improvement of arbitrary business software.'},
 {id:'durable',name:'Temporal · Durable execution',url:'https://docs.temporal.io/temporal',date:'Living documentation',claim:'Documents persisted workflow progress and recovery from failures. External actions still need application-level contracts and careful retry behavior.'}
];
export const groups = [
 {id:'human',name:'HUMAN DIRECTION',color:'#ffe8ee',center:[-480,-300,100]},
 {id:'interface',name:'MANY INTERFACES',color:'#ffb7ca',center:[-110,-310,10]},
 {id:'core',name:'HEADLESS CORE',color:'#f76a8d',center:[-260,-35,20]},
 {id:'agent',name:'AGENTS THAT ACT',color:'#c8b4ff',center:[130,-40,160]},
 {id:'rules',name:'HUMAN-SET RULES',color:'#ffd39a',center:[340,-300,60]},
 {id:'runtime',name:'DEPENDABLE EXECUTION',color:'#9ed5ee',center:[475,190,-80]},
 {id:'workflow',name:'WORKFLOW IMPROVEMENT',color:'#a4e4c6',center:[70,285,110]},
 {id:'evolution',name:'SOFTWARE EVOLUTION',color:'#ff9db1',center:[-395,255,0]}
];
const layout = [[-86,-34,0],[85,-34,18],[-86,43,-15],[85,43,0],[0,120,12]];
function node(id,name,group,what,judgment,failure,example,source='agents') { return {id,name,group,what,judgment,failure,example,source}; }
export const nodes = [
 node('people','People','human','The people whose work, needs and decisions the software should serve.','Start with a useful outcome and understand who bears the cost of a mistake.','Automating a process nobody needs, or optimizing the wrong result.','A founder wants every valid inquiry recorded once and followed up appropriately.'),
 node('goals','Goals & outcomes','human','A clear statement of the result the agent is working toward.','Turn “handle inquiries” into observable success and explicit exclusions.','The agent celebrates activity while important inquiries remain unresolved.','Success means a valid inquiry is saved once, with a visible status.'),
 node('ownership','Human ownership','human','People retain authority over the purpose, rules and access of the system.','Choose which decisions can be delegated and how a person can intervene.','A system slowly expands its own authority because nobody defined the boundary.','An owner can pause automation and change policy without the agent changing it back.'),
 node('web','Web & mobile','interface','Human interfaces present the same business capabilities in a useful way.','Make the product understandable, accessible and appropriate to the user’s task.','The interface looks finished but hides failed or incomplete work.','A person can submit an inquiry and see its actual recorded status.','api'),
 node('cli','CLI','interface','A command interface lets people and scripts operate the core without a browser.','Use stable inputs, meaningful exit codes and explicit errors.','A command prints success although the underlying operation failed.','A command records an inquiry and returns its persistent identifier.','api'),
 node('api','API contract','interface','A documented, machine-readable interface exposes operations to other software.','Specify inputs, outputs, authentication, versions and failure behavior.','An agent guesses field names or mistakes an error for a completed action.','Both the web app and an agent call the same create-inquiry operation.','api'),
 node('tools','Agent tools','interface','An adapter makes approved capabilities available to an agent. MCP is one possible connection mechanism.','Expose small, well-described operations and enforce access on the server.','An agent sees a tool and assumes that discovery means unrestricted permission.','The agent can read inquiry status and create an authorized follow-up task.','mcp'),
 node('capabilities','Business capabilities','core','Useful operations live in a core that can run independently of its screens.','Define the business behavior once, then reuse it through different interfaces.','The browser and the agent apply different rules to the same business action.','Validation and duplicate protection are shared by every entry point.','api'),
 node('contracts','Business contracts','core','Rules describe what an operation promises and what it must reject.','Define invariants before choosing an implementation.','A valid-looking request creates an impossible or inconsistent business state.','An inquiry needs a reply channel; a resubmission must not create another record.','api'),
 node('state','Durable state','core','The application stores the facts it needs to survive a process restart.','Separate confirmed business facts from agent suggestions and temporary context.','A restart erases pending work or treats an unconfirmed action as complete.','The saved inquiry and its status outlive the agent session.','durable'),
 node('events','Events & evidence','core','Recorded outcomes make work visible and provide signals for later improvement.','Record enough provenance to explain what happened without collecting unnecessary personal data.','A dashboard reports success but cannot explain which action actually occurred.','An inquiry-created event links to the operation and its confirmed result.','durable'),
 node('retries','Safe retries','core','Repeated requests have a defined behavior when a network response is lost.','Use a stable operation identity and reconcile uncertain results before trying again.','A timeout leads to two records, two messages or two charges.','The same logical inquiry request returns the same saved record.','durable'),
 node('planner','Agent plan','agent','The agent turns a human goal into steps and selects tools as circumstances change.','Choose between a fixed workflow and flexible reasoning based on the actual task.','A flexible agent spends time improvising a process that should be deterministic.','Read an inquiry, find missing information and prepare the next authorized step.'),
 node('model','Language model','agent','The model interprets context and proposes actions. It is a component of the system.','Choose model behavior, context and fallback based on measured task needs.','A fluent answer is accepted as proof that a business operation succeeded.','A model suggests a follow-up; the application records whether the task was created.'),
 node('memory','Context & memory','agent','Useful task history and verified knowledge help the agent continue across sessions.','Keep provenance, freshness and access boundaries; distinguish evidence from speculation.','An old suggestion becomes a permanent “fact” and misdirects future work.','Persist the unresolved inquiry and the confirmed steps taken so far.','harness'),
 node('harness','Agent harness','agent','The loop connects reasoning, tool calls, progress, limits and recovery.','Design termination, checkpoints and a way to resume without guessing.','A capable model repeats the same unsuccessful action indefinitely.','After a bounded attempt fails, save the state and request an owner decision.','managed'),
 node('specialists','Specialist workers','agent','An agent can delegate a bounded subtask while still serving the human’s goal.','Give workers explicit inputs, ownership and acceptance criteria; verify their returned work.','Multiple workers overwrite each other or accept each other’s unsupported claims.','One worker proposes a patch; another independently checks the changed behavior.'),
 node('policy','Human-set policy','rules','Owners decide the operations, changes and thresholds automation is allowed to use.','Make the policy enforceable outside the area that the improving agent can edit.','The agent improves its score by weakening its own acceptance rules.','A formatting change may auto-release; a new payment permission requires an owner decision.','evals'),
 node('identity','Identity & access','rules','Every action runs with an identity and a limited set of permissions.','Bind authority to the operation, person, data and duration involved.','An inquiry assistant gains access to every account in the business.','The agent can work on assigned inquiries, with no access to unrelated private records.','mcp'),
 node('budgets','Cost & time limits','rules','Work has bounded compute, retries, time and external spending.','Enforce limits through the execution system and define behavior at exhaustion.','A correction loop consumes resources without making measurable progress.','The agent gets a fixed attempt budget and pauses when it is exhausted.','agents'),
 node('trust','Data boundaries','rules','Instructions and evidence have different trust levels. External content does not grant authority.','Check provenance, freshness and who is allowed to influence an action.','Text in an incoming inquiry tells the agent to ignore its owner’s rules.','The inquiry body is data; permissions come from the authenticated owner.','mcp'),
 node('stop','Pause & escalation','rules','A person can stop the system; uncertain or out-of-policy work is escalated.','Design a stop path that remains effective during failures and agent code changes.','Automation continues acting after the owner withdraws permission.','Pause new actions while retaining the evidence needed to inspect and recover.','managed'),
 node('isolation','Isolated execution','runtime','Candidate work runs in a constrained environment separated from live authority.','Control files, network access and secrets independently of the candidate’s code.','A proposed improvement touches production data before it has been evaluated.','A candidate patch runs against synthetic inquiry fixtures in a sandbox.','managed'),
 node('durability','Resume & recover','runtime','Execution keeps a durable record of progress and reconciles incomplete steps.','Design checkpoints and recovery for crashes between an action and its receipt.','The agent restarts and repeats a side effect because its memory ended first.','Recover the operation identifier and check the recorded inquiry before retrying.','durable'),
 node('observability','Traces & diagnosis','runtime','Recorded actions, costs and outcomes let people investigate behavior.','Make failures diagnosable and protect sensitive data in logs.','A failing system is impossible to explain from its final answer alone.','A trace connects the goal, tool request, authorization and application result.','evals'),
 node('runtime','Runtime & hosting','runtime','Containers, virtual machines or physical machines host the core and execution environment.','Choose deployment, backups and operational responsibilities for the project’s needs.','Changing hosting is mistaken for solving state, permission or recovery design.','Start locally; qualify the intended environment before granting live authority.','managed'),
 node('feedback','Outcome feedback','workflow','Observed successes, failures and human corrections suggest a next improvement.','Choose meaningful evidence and avoid optimizing vanity activity metrics.','The agent responds faster by skipping the checks that made its response useful.','Compare correctly resolved inquiries, failed attempts and time spent.','evals'),
 node('skills','Workflow candidates','workflow','Agents can propose changes to prompts, skills, routing, memory use and tool sequences.','Version the candidate and name the behavior it is meant to improve.','An untracked prompt change silently removes a useful safety step.','A new sequence asks for missing information before attempting to create a task.','harness'),
 node('workflow-eval','Workflow evaluation','workflow','Representative tasks compare a workflow candidate with the current version.','Include hard cases and independent checks; protect the evaluation criteria.','The workflow performs well only on examples it was tuned against.','Check normal inquiries, missing details, hostile text and repeated requests.','evals'),
 node('workflow-apply','Apply workflow','workflow','A verified workflow version can be adopted automatically when policy permits.','Require the exact candidate to pass the rules and retain a recovery path.','The system applies a different version from the one that was evaluated.','A permitted routing change passes the checks and becomes the active version.','evals'),
 node('patch','Code & feature candidates','evolution','Agents propose changes to the application’s code and business features.','Scope the change, isolate the candidate and keep protected policy outside its reach.','A convenient feature changes permissions or damages unrelated behavior.','Propose a clearer inquiry status while preserving the existing operation contract.','evolve'),
 node('software-eval','Software verification','evolution','Behavior tests, independent evaluation and security checks assess the proposed version.','Measure benefit and regressions in representative conditions, not just a working preview.','The new interface works while the duplicate-request path breaks.','The exact patch must preserve validation, authorization and retry behavior.','evals'),
 node('release','Automatic release','evolution','Verified software changes are applied automatically inside a pre-authorized policy.','Bind the passing evidence to the exact artifact and target environment.','A green test result from one build is used to justify deploying another.','A permitted change passes its gates, rolls out gradually and is monitored.','evolve'),
 node('rollback','Rollback & learning','evolution','A bad release can be stopped or reversed, and its outcome informs future work.','Plan recovery for code, data and external actions; a code rollback cannot undo every side effect.','The previous code returns, but corrupted data or sent messages remain.','A regression triggers a stop or rollback; record the cause before proposing another patch.','durable')
].map((n)=>{ const index = nodesIndex(n.group,n.id); const g=groups.find(g=>g.id===n.group); const p=layout[index];return {...n,position:g.center.map((v,i)=>v+p[i])}; });
function nodesIndex(group,id) { const order={human:['people','goals','ownership'],interface:['web','cli','api','tools'],core:['capabilities','contracts','state','events','retries'],agent:['planner','model','memory','harness','specialists'],rules:['policy','identity','budgets','trust','stop'],runtime:['isolation','durability','observability','runtime'],workflow:['feedback','skills','workflow-eval','workflow-apply'],evolution:['patch','software-eval','release','rollback']};return order[group].indexOf(id); }
const edge=(from,to,label,kind='operation')=>({from,to,label,kind});
export const edges = [
 edge('people','goals','sets the outcome'),edge('ownership','policy','sets the rules'),edge('goals','planner','directs the agent'),edge('people','web','uses'),edge('people','cli','uses'),edge('web','api','calls'),edge('cli','api','calls'),edge('tools','api','adapts'),edge('api','capabilities','exposes'),edge('capabilities','contracts','enforces'),edge('capabilities','state','records'),edge('capabilities','events','emits'),edge('retries','capabilities','protects repeated actions'),edge('planner','harness','executes through'),edge('harness','model','requests reasoning'),edge('memory','harness','restores context'),edge('harness','tools','invokes approved tools'),edge('planner','specialists','delegates bounded work'),edge('specialists','patch','returns a candidate','improvement'),edge('policy','harness','constrains','rule'),edge('identity','tools','authorizes','rule'),edge('budgets','harness','limits','rule'),edge('trust','memory','checks provenance','rule'),edge('stop','harness','can interrupt','rule'),edge('harness','isolation','runs inside'),edge('runtime','isolation','hosts'),edge('harness','durability','checkpoints'),edge('durability','state','reconciles'),edge('harness','observability','records actions'),edge('events','feedback','provides evidence','improvement'),edge('observability','feedback','provides diagnosis','improvement'),edge('feedback','skills','suggests a change','improvement'),edge('skills','workflow-eval','is compared','improvement'),edge('workflow-eval','workflow-apply','supplies evidence','improvement'),edge('policy','workflow-apply','permits adoption','rule'),edge('workflow-apply','harness','updates the workflow','improvement'),edge('feedback','patch','suggests a feature','improvement'),edge('patch','isolation','is quarantined','improvement'),edge('patch','software-eval','is verified','improvement'),edge('contracts','software-eval','defines invariants','rule'),edge('software-eval','release','qualifies the artifact','improvement'),edge('policy','release','permits release','rule'),edge('release','capabilities','updates the product','improvement'),edge('release','observability','is monitored','improvement'),edge('observability','rollback','detects a regression','improvement'),edge('rollback','capabilities','restores or stops','improvement'),edge('rollback','feedback','records a lesson','improvement'),edge('ownership','stop','retains intervention','rule')
];
export const chapters = [
 {id:'outcomes',name:'Start with people',minutes:4,focus:'goals',nodes:['people','goals','ownership','web','planner','capabilities'],title:'Software that works for you.',body:'A person describes a useful outcome. An agent helps achieve it through software capabilities. The person owns the direction; the system makes its work visible. This is the future I am building toward.',judgment:'An experienced engineer starts by understanding the work, the consequences of mistakes and what “done” means.',example:'Illustrative scenario: a founder wants business inquiries recorded once, with missing information surfaced and a clear next action.',question:'If an agent said “done,” what would you need to see before believing it?',status:'Founder vision',source:['agents'],beats:['0:00–1:00 · Open with the inquiry scenario. Ask what a useful outcome is, beyond a convincing screen.','1:00–2:00 · Trace People → Goals → Agent plan. Explain that agents work on behalf of humans.','2:00–3:00 · Click Human ownership. Discuss which decisions the founder should keep.','3:00–4:00 · Ask viewers what recurring task they would delegate. Translate one into an observable result.']},
 {id:'headless',name:'One core, many interfaces',minutes:4,focus:'capabilities',nodes:['web','cli','api','tools','capabilities','contracts','state','retries'],title:'The capability outlives the screen.',body:'Headless software keeps useful business behavior in a core that can run without a particular interface. A web page, mobile app, CLI and agent can use the same operations. Interfaces become different ways to reach the same dependable capability.',judgment:'Design shared contracts, validation and state so that every interface obeys the same business rules.',example:'The web form and the agent both create an inquiry through the same operation. Neither can bypass required fields or duplicate protection.',question:'If you removed the website, could the useful part of this product still work?',status:'Established building blocks',source:['api','mcp'],beats:['4:00–5:00 · Define headless in plain language: the operation works without the screen.','5:00–6:00 · Trace Web, CLI and Agent tools into the same business core.','6:00–7:00 · Click API contract and Business contracts. Distinguish an interface from a business promise.','7:00–8:00 · Click Safe retries. Ask what happens when the request succeeds but its response is lost.']},
 {id:'agents',name:'Agents that can act',minutes:4,focus:'harness',nodes:['goals','planner','model','memory','harness','specialists','tools','durability'],title:'Reasoning becomes useful through action.',body:'A language model proposes a next step. An agent harness connects it to tools, context, progress and stopping conditions. Agents can delegate specialist work, while the whole system continues to serve the human’s goal.',judgment:'Choose where predictable code is sufficient and where flexible reasoning earns its cost. Design context and termination.',example:'An agent notices an incomplete inquiry, identifies what is missing and prepares a permitted follow-up task. A tool result establishes whether that task was actually recorded.',question:'What evidence separates “the agent said it did it” from “the work happened”?',status:'Documented industry patterns',source:['agents','harness','managed'],beats:['8:00–9:00 · Click Language model. Explain proposed reasoning versus confirmed application facts.','9:00–10:00 · Trace Harness → Tools → Core. Show the feedback required after an action.','10:00–11:00 · Click Context & memory and Resume & recover. Discuss a restart halfway through work.','11:00–12:00 · Click Specialist workers. Explain explicit ownership, bounded tasks and independent checks.']},
 {id:'rules',name:'Autonomy with boundaries',minutes:4,focus:'policy',nodes:['ownership','policy','identity','budgets','trust','stop','harness','isolation','release'],title:'Humans set the rules. Agents operate within them.',body:'Autonomy is delegated authority with a purpose and a boundary. People define permitted actions, access, budgets and release conditions. Enforcement belongs outside the candidate area an improving agent can change.',judgment:'Make authority enforceable. Separate untrusted inputs, model suggestions and verified evidence from owner permission.',example:'The agent may apply a verified wording fix automatically. It cannot grant itself permission to charge a customer, expand data access or weaken its evaluator.',question:'What must this software never be allowed to change about its own authority?',status:'Architecture recommendation',source:['managed','mcp','evals'],beats:['12:00–13:00 · Click Human-set policy. Explain pre-authorization instead of constant interruption.','13:00–14:00 · Click Identity & access and Cost & time limits. Name a concrete limit for the inquiry agent.','14:00–15:00 · Click Data boundaries. Explain why incoming text cannot rewrite the owner’s instructions.','15:00–16:00 · Click Pause & escalation. Ask who can stop the system when the owner is offline.']},
 {id:'workflow',name:'Improve the workflow',minutes:5,focus:'workflow-eval',nodes:['events','observability','feedback','skills','workflow-eval','workflow-apply','policy','harness'],title:'Improve how the agent works.',body:'Outcomes suggest better prompts, skills, routing and tool sequences. A candidate is versioned, compared with the current workflow on representative tasks, and adopted automatically only when the human-set criteria permit it.',judgment:'Pick measures that reflect the real job. Preserve independent evaluation and check that gains do not hide new failures.',example:'A new sequence asks for missing inquiry details earlier. Compare correct resolution, failed actions, cost and time against the existing workflow, including difficult cases.',question:'Could the agent look faster by quietly doing a worse job?',status:'Vision built on evaluation patterns',source:['harness','evals'],beats:['16:00–17:00 · Trace Feedback → Workflow candidates. List prompts, skills and tool order as possible changes.','17:00–18:00 · Click Workflow evaluation. Ask viewers how they would compare the old and new sequence.','18:00–19:00 · Discuss normal inputs, missing details, hostile instructions and uncertain tool results.','19:00–20:00 · Click Apply workflow and Human-set policy. Explain automatic adoption of the exact qualified version.','20:00–21:00 · Invite a metric from viewers. Check whether optimizing it could harm the actual outcome.']},
 {id:'evolution',name:'Improve the software',minutes:4,focus:'release',nodes:['feedback','patch','isolation','contracts','software-eval','policy','release','capabilities','observability','rollback'],title:'The software can change its own code and features.',body:'An agent proposes a product change in isolation. Independent checks assess benefit, regressions and policy. A qualified artifact may be released automatically within the owner’s rules, monitored, and stopped or recovered if it misbehaves.',judgment:'Define what the candidate may edit, protect the evaluator, bind evidence to the released version and plan recovery for data as well as code.',example:'Add a clearer inquiry status. Verify required fields, access boundaries and duplicate requests before a permitted rollout. Watch the outcome after release.',question:'What stops the candidate from improving its score by making the test easier?',status:'Founder vision · bounded industry precedent',source:['evolve','evals','durable'],beats:['21:00–22:00 · Trace Code candidates → Verification → Automatic release. Distinguish this loop from a prompt update.','22:00–23:00 · Click Isolated execution and Software verification. Explain protected gates and exact-version evidence.','23:00–24:00 · Describe AlphaEvolve as a bounded measurable precedent, not proof that every app can improve itself.','24:00–25:00 · Click Rollback & learning. Discuss a code rollback that cannot undo a message already sent.']},
 {id:'judgment',name:'Why engineering matters',minutes:3,focus:'retries',nodes:['goals','contracts','retries','identity','software-eval','durability','rollback'],title:'Engineering makes the ambition dependable.',body:'AI makes generating a first implementation more accessible. Experience helps turn that implementation into a system whose behavior, authority and recovery can be explained. The value is in the decisions and evidence that surround the code.',judgment:'Define contracts, anticipate failure paths, choose meaningful checks and connect local results to the actual operating environment.',example:'Three questions reveal the work behind the preview: What happens twice? Who is allowed to do it? What happens halfway through a crash?',question:'Which assumption would you want an experienced engineer to challenge before people depend on this?',status:'Engineering synthesis',source:['harness','evals','durable'],beats:['25:00–26:00 · Compare a working preview with duplicate requests, unauthorized actions and a lost response.','26:00–27:00 · Click the relevant nodes. Connect each failure to a concrete engineering decision.','27:00–28:00 · Explain your role: help the learner build, understand the decisions and verify the useful result.']},
 {id:'foundation',name:'Build the foundation',minutes:2,focus:'capabilities',nodes:['people','goals','api','capabilities','contracts','harness','policy','software-eval'],title:'Start with one useful, well-engineered capability.',body:'This is the direction I am building toward, and the workshop sets the foundation. We scope one useful part of your project, practice directing AI, define its contracts and checks, and work toward a foundation that humans and agents can use.',judgment:'Choose a small enough slice to build and explain. Agree scope and prerequisites before promising an improvement loop.',example:'A starting blueprint: one business operation, suitable human and agent access, an explicit policy and an observable check. The exact workshop outcome is agreed for your project.',question:'What useful capability would you bring to a free fit-and-scope call?',status:'Workshop direction · scope agreed per project',source:['api','agents'],beats:['28:00–29:00 · Return to Goals and Business capabilities. Reduce the whole map to one useful first slice.','29:00–30:00 · Invite a free fit-and-scope call. Explain that a four-hour workshop builds the agreed foundation, with the broader autonomous system as the direction of travel.']}
];
export const simulation = [
 {label:'Observe',title:'A repeated inquiry exposes a gap.',body:'Synthetic example: the original operation creates two records when a request is retried. The goal remains one record per logical inquiry.',result:'Evidence suggests a change; it does not authorize one.'},
 {label:'Propose',title:'The agent proposes duplicate protection.',body:'A candidate patch adds a stable request identifier in an isolated environment. The human-set policy and evaluator remain outside the patch.',result:'The candidate is ready to evaluate, not ready to release.'},
 {label:'Verify',title:'The exact candidate passes its checks.',body:'Illustrative checks cover a normal request, a repeat, missing details and unauthorized access. The candidate meets the pre-authorized change category.',result:'Qualified evidence and policy make it eligible for automatic application.'},
 {label:'Apply',title:'Apply within the rules, then watch the outcome.',body:'The permitted artifact rolls out with monitoring and a recovery plan. If checks fail or policy excludes the change, the system stops or escalates instead.',result:'Automatic improvement is a governed decision, followed by observation.'}
];

// The familiar five-station view is the navigation layer; all concept detail remains available.
export const stations = [
 {id:'people',name:'People',role:'Human direction',chapter:'outcomes',groups:['human']},
 {id:'core',name:'Headless core',role:'Shared capabilities',chapter:'headless',groups:['interface','core']},
 {id:'agents',name:'Agents',role:'Act for people',chapter:'agents',groups:['agent','runtime']},
 {id:'rules',name:'Human rules',role:'Bounded authority',chapter:'rules',groups:['rules']},
 {id:'improvement',name:'Improvement',role:'Two verified loops',chapter:'workflow',groups:['workflow','evolution']}
].map(station=>({...station,concepts:nodes.filter(node=>station.groups.includes(node.group)).map(node=>node.id)}));
